language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
    - "node"
jobs:
  include:
    - script: yarn test
    - stage: GitHub pages
      script: yarn build
      deploy:
        provider: pages
        github_token: $github_token
        skip_cleanup: true
        local_dir: build
        on:
          branch: master